require "ysd_plugin_booking_extensions/version"
require "ysd_plugin_booking_extensions/sinatra/ysd_sinatra_booking_resources_maintenance"
require "ysd_plugin_booking_extensions/sinatra/ysd_sinatra_booking_users_management"
require "ysd_plugin_booking_extensions/sinatra/ysd_sinatra_booking_users_management_rest_api"

require "ysd_plugin_booking_extensions/yito_extension/ysd_plugin_booking_extensions_extension"
require "ysd_plugin_booking_extensions/ysd_plugin_booking_extensions_init"

module YsdPluginBookingExtensions
  # Your code goes here...
end
